// Package routes provides automatic route registration.
// This file is auto-generated by 'go generate'. Do not edit manually.
//
//go:generate go run ../scripts/generate-routes.go

package routes

// Import all route namespaces to trigger their init() functions
import (
	_ "github.com/jean-jacket/grss/routes/apple"
	_ "github.com/jean-jacket/grss/routes/example"
	_ "github.com/jean-jacket/grss/routes/github"
	_ "github.com/jean-jacket/grss/routes/youtube"
)
