// generate-routes.go - Automatically generates routes/routes.go with all namespace imports
//
// Usage: go run scripts/generate-routes.go
//
// This script scans the routes/ directory for namespaces (subdirectories)
// and generates a routes.go file that imports all of them, triggering their
// init() functions for automatic route registration.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

const routesTemplate = `// Package routes provides automatic route registration.
// This file is auto-generated by 'go generate'. Do not edit manually.
//
//go:generate go run ../scripts/generate-routes.go

package routes

// Import all route namespaces to trigger their init() functions
import (
{{- range .Namespaces}}
	_ "github.com/jean-jacket/grss/routes/{{.}}"
{{- end}}
)
`

func main() {
	// Get the routes directory
	routesDir := "routes"
	if len(os.Args) > 1 {
		routesDir = os.Args[1]
	}

	// Find all namespace directories
	namespaces, err := findNamespaces(routesDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error finding namespaces: %v\n", err)
		os.Exit(1)
	}

	if len(namespaces) == 0 {
		fmt.Fprintf(os.Stderr, "Warning: No route namespaces found in %s\n", routesDir)
	}

	// Sort namespaces for consistent output
	sort.Strings(namespaces)

	// Generate the routes.go file
	tmpl, err := template.New("routes").Parse(routesTemplate)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing template: %v\n", err)
		os.Exit(1)
	}

	outputFile := filepath.Join(routesDir, "routes.go")
	f, err := os.Create(outputFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error creating output file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	data := struct {
		Namespaces []string
	}{
		Namespaces: namespaces,
	}

	if err := tmpl.Execute(f, data); err != nil {
		fmt.Fprintf(os.Stderr, "Error executing template: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated %s with %d namespaces\n", outputFile, len(namespaces))
	for _, ns := range namespaces {
		fmt.Printf("  - %s\n", ns)
	}
}

// findNamespaces scans the routes directory for namespace subdirectories
func findNamespaces(routesDir string) ([]string, error) {
	var namespaces []string

	entries, err := os.ReadDir(routesDir)
	if err != nil {
		return nil, err
	}

	for _, entry := range entries {
		// Skip non-directories
		if !entry.IsDir() {
			continue
		}

		name := entry.Name()

		// Skip special directories
		if name == "registry" || strings.HasPrefix(name, ".") || strings.HasPrefix(name, "_") {
			continue
		}

		// Check if directory has any .go files (indicating it's a namespace)
		hasGoFiles, err := hasGoFiles(filepath.Join(routesDir, name))
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: Error checking %s: %v\n", name, err)
			continue
		}

		if hasGoFiles {
			namespaces = append(namespaces, name)
		}
	}

	return namespaces, nil
}

// hasGoFiles checks if a directory contains any .go files
func hasGoFiles(dir string) (bool, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return false, err
	}

	for _, entry := range entries {
		if !entry.IsDir() && strings.HasSuffix(entry.Name(), ".go") && !strings.HasSuffix(entry.Name(), "_test.go") {
			return true, nil
		}
	}

	return false, nil
}
